### ISSUE TITLE
Garbage collection of CUDS objects

### ISSUE THREAD

**Issue by yoavnash** [simphony/osp-core#598]
Once a CUDS object has been loaded to the memory, it will stay there until the program exits due to the registry that prevents the built-in garbage collector to be applied to it. This is unsustainable for the long run and therefore should be improved.

**Comment by kysrpex** [comment]
Just laying an option (FYI but also as a note to myself for implementing the upgrade).

If one checks the code of OSP-core, the registry seems to be used mainly for loading CUDS from the sessions. The question of whether we want to have a registry or not follows from another question: Do we want to be able to refer to an individual without having to search for it, starting from the session wrapper? I think the answer is definitely yes.

It is not so obvious when thinking of UUIDS, because it may be cumbersome to work with them. But think of issue #597. It may be even useful to have a registry that references the cuds by annotation properties. Or even to have more registries for other properties.

So I think that improving the registry is the way to go. What may first come to mind, is to implement a LRU cache and delete the older references from the registry. If the CUDS has another reference in memory it will be kept, otherwise it will be removed from memory.

However, this raises the issue of what happens when a CUDS reference is deleted and then reloaded shortly thereafter. If the LRU cache is too small, this will create further performance issues. And it would be indeed very dumb, as the cache would be of a fixed size and memory would be wasted. Therefore, what would make sense is to have a dynamically sized cache. 

There could be a maximum and minimum cache size, and it could vary in between following some kind of access-based or time-based algorithm. Every time the cache (registry) is accessed, it could register whether it was a miss or not. Based on that data, a rolling average of misses could be kept, over a period of accesses. When the rolling average approaches one, the size of the cache should increase (not necessarily linearly). The converse should also happen: when the rolling average approaches zero, the size of the cache should decrease. This would eventually lead to an equilibrium size, dependent on the workload. The size of the rolling average window would be what determines how quickly the cache increases/decreases when the workload is abruptly changed. If there is volatility in the workload, this might be a problem, but this might be though of just later. Probably, then one would need to change the size of the rolling window also dynamically.

This probably needs more engineering, but is a good idea to start.

**Comment by kysrpex** [comment]
With SimPhoNy v4, this issue has become outdated. OntologyIndividual objects do not actually hold any information, but are just a sort of "pointer" to the underlying RDF graph. One may create as many OntologyIndividual objects with the same IRI as desired, when one is updated, all are updated, because every time they are accessed, they are in fact accessing the RDF graph, which is what gets modified. 

Therefore, OntologyIndividual objects are just garbage collected automatically sometime after they go out of scope.
