### ISSUE TITLE
Data properties not explicitly linked to an entity

### ISSUE THREAD

**Issue by yzuuang** [simphony/osp-core#642]
When a data property that doesn't specify `rdfs:domain` and `rdfs:range` explicitly, osp-core fails to recognize it as an attribute.
For example: to create a cuds object from FOAF ontology
```python
person = foaf.Person(nick="nickname")
```
with `foaf:nick` defined as below
```
<rdf:Property rdf:about="http://xmlns.com/foaf/0.1/nick" vs:term_status="testing" rdfs:label="nickname" rdfs:comment="A short informal nickname characterising an agent (includes login identifiers, IRC and other chat nicknames).">
  <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#DatatypeProperty"/>
  <rdfs:isDefinedBy rdf:resource="http://xmlns.com/foaf/0.1/"/>
</rdf:Property>
```
will cause an error
```console
ValueError: Invalid key foaf.nick
```

**Comment by pablo-de-andres** [comment]
For more info, see how [`__setattr__`](https://github.com/simphony/osp-core/blob/master/osp/core/cuds.py#L847) calls [`_get_attribute_by_argname`](https://github.com/simphony/osp-core/blob/71b05420c47eefc0d968985b6948a3b2d553e7b7/osp/core/cuds.py#L824), which checks that the attribute belongs to the oclass ([here](https://github.com/simphony/osp-core/blob/71b05420c47eefc0d968985b6948a3b2d553e7b7/osp/core/ontology/oclass.py#L175))

**Comment by kysrpex** [comment]
In order to solve this, I think that first we should decide on a syntax to access such data properties, and #416, is very relevant in this sense. The **TLDR** of such issue is:

__Current behavior__

> | | functional DatatypeProperty | functional ObjectProperty | non-functional DatatypeProperty | non-functional ObjectProperty|
> |--- | --- | --- | --- | ---|
> |add() |  | not supported | not supported | x |
> |dot | x | not supported  | not supported |  |

One of the two behaviors below is the desired one, the actual one is not specified on the issue.

__Desired behavior 1__

> | | functional DatatypeProperty | functional ObjectProperty | non-functional DatatypeProperty | non-functional ObjectProperty|
> |--- | --- | --- | --- | ---|
> |add() | x | x | x | x |
> |dot | x | x  |  |  |

__Desired behavior 2__

> | | functional DatatypeProperty | functional ObjectProperty | non-functional DatatypeProperty | non-functional ObjectProperty|
> |--- | --- | --- | --- | ---|
> |add() | x | x | x | x |
> |dot | x |   | x |  |

**I would go for 1**, as from the dot notation we already expect just one output and from get we already expect a list (the only exception is when one puts a uid in `get`).

**Comment by kysrpex** [comment]
I actually found a better solution:

| | functional DatatypeProperty | functional ObjectProperty | non-functional DatatypeProperty | non-functional ObjectProperty|
|--- | --- | --- | --- | ---|
|add() |  | x |  | x |
|dot | x |  |  |  |
|[ ] (\_\_getitem\_\_, \_\_setitem\_\_) | x | x | x | x |

I realized this because when an attribute is set multiple times, I need to know somehow which of the literals I am changing. This also allows to specify an object inside the brackets [ ]. We could even get rid of add using this.

**Comment by kysrpex** [comment]
The change is in progress, so far for the attributes it's done:

```python
In [1]: from osp.core.namespaces import city, foaf
   ...: freiburg = city.City(name='Freiburg')
   ...: print(freiburg[foaf.nick])
   ...: freiburg[foaf.nick] += {'Die Stadt'}
   ...: print(freiburg[foaf.nick])
   ...: freiburg[foaf.nick] |= {'Eine Stadt'}
   ...: print(freiburg[foaf.nick])
   ...: freiburg[foaf.nick] += {'Universitätsstadt'}
   ...: print(freiburg[foaf.nick])
   ...: freiburg[foaf.nick].add('Another nickname')
   ...: print(freiburg[foaf.nick])
   ...: freiburg[foaf.nick].remove('Another nickname')
   ...: print(freiburg[foaf.nick])
   ...: freiburg[foaf.nick].discard('Another nickname')
   ...: print(freiburg[foaf.nick])
   ...: freiburg[foaf.nick].update({'Another nickname'})
   ...: print(freiburg[foaf.nick])
   ...: freiburg[foaf.nick].add('Another nickname')
   ...: print(freiburg[foaf.nick])
   ...: freiburg[foaf.nick].clear()
   ...: print(freiburg[foaf.nick])
   ...: freiburg[foaf.nick] = {'Nick 1', 'Nick 2'}
   ...: print(freiburg[foaf.nick])
RDFLib Version: 6.0.0
set()
{'Die Stadt'}
{'Die Stadt', 'Eine Stadt'}
{'Die Stadt', 'Universitätsstadt', 'Eine Stadt'}
{'Another nickname', 'Die Stadt', 'Universitätsstadt', 'Eine Stadt'}
{'Die Stadt', 'Universitätsstadt', 'Eine Stadt'}
{'Die Stadt', 'Universitätsstadt', 'Eine Stadt'}
{'Another nickname', 'Die Stadt', 'Universitätsstadt', 'Eine Stadt'}
{'Another nickname', 'Die Stadt', 'Universitätsstadt', 'Eine Stadt'}
set()
{'Nick 2', 'Nick 1'}
```

Essentially the `__getitem__` method returns a subclass of `collections.abc.MutableSet`, that when modified in-place changes the attribute of the CUDS. `__setitem__` completely replaces the attribute of the CUDS with the values specified instead.

**Comment by kysrpex** [comment]
The PR solving this is now almost ready, so I think we better continue the discussion [here](https://github.com/simphony/osp-core/discussions/696).
